export const locations = {
  Bellmere: ["Bellbrook Pl", "Parkwood Pl", "Riverside Circuit", "Swann Rd"],
  Caboolture: [
    "Crawford St",
    "Bluestar Circuit",
    "Cutler St",
    "Craigslea Dr",
    "Goldencrest St",
    "Water Fern Dr",
    "Condamine St",
    "Kipling St",
    "Hazelwood Court",
    "Topaz St",
    "Cullawong Dr",
  ],
  Clontarf: ["Long St", "Watson St"],
  "Deception Bay": [
    "Cockatiel Court",
    "Magpie Court",
    "Miner Court",
    "Breakwater Court",
    "Richard Court",
    "Headland Pl",
  ],
  Donnybrook: ["Amy St"],
  "Eatons Hill": ["Windrush Close", "Drapers Rd"],
  Griffin: [
    "Lemongrass Circuit",
    "Clements St",
    "Vermilion Ave",
    "Bramble St",
    "Floradel St",
  ],
  Joyner: ["Jean Close"],
  Kallangur: [
    "Azalea Court",
    "Swordgrass Court",
    "Kahala Court",
    "Winter Rd",
    "Lillypilly Court",
    "Mark St",
    "Allison Dr West",
  ],
  "Kippa-Ring": ["Abelia Cres"],
  Lawnton: ["Todds Rd"],
  "Mango Hill": [
    "Amber Close",
    "Mercury Pde",
    "Peridot Cres",
    "Rose St East",
    "Barnes St",
  ],
  Morayfield: [
    "Allyra Dr",
    "Bilby Dr",
    "Crestwood Ave",
    "Long Court",
    "Telopea Pl",
    "Treedale St",
  ],
  "Murrumba Downs": ["Hillcrest Court", "Tokely Court", "Mires Cres"],
  Narangba: [
    "Baphal Cres",
    "Bendee Court",
    "Boobook Court",
    "Coronata Cres",
    "Jinibara Cres",
    "King Parrot Close",
    "Mapleton Court",
    "Satinash St",
    "Wedgetail Circuit",
    "Wentworth Pl",
  ],
  "North Lakes": [
    "Koala Close",
    "Melville Pde",
    "Longer Circuit",
    "Nicklaus Pde",
    "Lanagan Circuit",
  ],
  Petrie: ["Eacham St", "Normanhurst Court", "Boona St", "Eucumbene Dr"],
  Redcliffe: ["Silvester St"],
  Rothwell: ["Morris Rd", "Casuarina Court"],
  "Sandstone Point": ["Clark Tce", "Mossman Way"],
  "Upper Caboolture": [
    "Riverparks Way",
    "Sunflower Cres",
    "Riflebird Dr",
    "Pauls Rd",
    "Arcadia St",
  ],
  Warner: [
    "Allchin Court",
    "Carlingford Circuit",
    "Granola Close",
    "Kidston Cres",
    "Mondial Dr",
    "Helen Cres",
    "Jean Close",
    "Blue Mountain Cres",
  ],
  "Albany Creek": [
    "Longreef Court",
    "Kosta Place",
    "Somerset Court",
    "The Boulevard",
  ],
  Aspley: ["Stoneycroft St", "Trouts Rd"],
  "Bridgeman Downs": ["Myall Place"],
  "Bray Park": [
    "Sparkes Road",
    "Evergreen Ave",
    "Magellan Court",
    "Nottingham Pde",
  ],
  "Bracken Ridge": [
    "Emma St",
    "Annie St",
    "Pilgrim Pl",
    "Paora St",
    "Randwick St",
    "Village Way",
    "Whyalla Close",
  ],
  Carseldine: ["Beams Road", "Riesling St"],
  Clayfield: ["Bonney Ave"],
  "Bald Hills": ["Arnica Cres", "Topham St", "Gympie Rd", "Paladin Pl"],
  Boondall: ["College Way"],
  Stafford: ["Minimine St"],
  "Everton Park": ["Flockton St", "Bunny St", "Hornby St"],
  "Everton Hills": ["Illawarra St"],
  "Ferny Grove": ["Greenfern Pl"],
  Enoggera: ["Samford Rd", "Hurdcotte St"],
  Geebung: ["Blackwood St"],
  Grange: ["Daisy St", "Howard St", "Myrtle St"],
  Northgate: ["Parker Ave", "O'Farrell Ave"],
  "Upper Kedron": ["Kingfisher Dr"],
  Banyo: ["Witt St"],
  "Wavell Heights": ["Sugarloaf St"],
  "Chermside West": ["Graymond St"],
  McDowall: ["Hughes St"],
  Keperra: ["Cobalt St"],
  Mitchelton: ["Essex St"],
  Deagon: ["Board St"],
  Zillmere: ["Zillmere Rd"],
  Algester: ["Triantha St", "Cordia St", "Cupania St"],
  Carina: ["Banbury St", "Stanley Rd"],
  Calamvale: ["Benhiam St", "Carnation Cres", "Golden Ave"],
  "Coopers Plains": ["Keeling St"],
  "Eight Mile Plains": ["Bordeaux St", "Kirstin St"],
  "Holland Park West": ["Captain St"],
  Jimboomba: ["Manning St", "Dwyer Pl"],
  Kuraby: ["Paloma Pl"],
  Moorooka: ["Citrus St", "Derek St", "Desanne Pl", "Rachael St"],
  "Upper Mt Gravatt": ["Lindwall St", "Kempsie Rd"],
  "Manly West": ["Talwong St", "Hargreaves Rd"],
  Mansfield: ["Picardie Close", "Tandanya St"],
  Parkinson: ["Daintree Dr"],
  "Rochedale South": ["Underwood Rd", "Rothon Dr", "Narelle Cres"],
  Runcorn: ["Calliope St"],
  Salisbury: ["Golda Ave"],
  "Sunnybank Hills": ["Hellawell Rd"],
  Tarragindi: ["Kuring Gai Ave"],
  Wishart: ["Anise St"],
  "Alexandra Hills": [
    "Justin Court",
    "Garter St",
    "Classic Court",
    "Stovold St",
    "Vienna Rd",
    "Bluebell St",
  ],
  Belmont: ["Mitchell Pl"],
  Birkdale: ["Burbank Rd", "Estelle St"],
  Bulimba: ["Birkala St"],
  Capalaba: [
    "Coolnwynpin Way",
    "Quentin St",
    "Greenfield Rd",
    "Gundagai Dr",
    "Springbrook Dr",
    "Spirit Dr",
    "Lorina Court",
    "Jacaranda Rd",
    "Koala Pl",
    "Tipperary Court",
  ],
  Carindale: ["Southview Cres", "Linwood St"],
  Cleveland: ["Carolina St", "Lowrie Court", "Passage St", "Mergowie Dr"],
  Ormiston: ["Bainbridge St East", "Parnell St"],
  "Mount Cotton": [
    "Hibiscus Dr",
    "Elkhorn St",
    "Myrtle Pl",
    "Sugar Gum Ave",
    "Persian Close",
  ],
  "Redland Bay": [
    "Teal Close",
    "Phillip St",
    "Valencia Springs Dr",
    "Balsam St",
    "Ebony Cres",
    "Dennison Court",
    "Huntly Pl",
    "Moreton View Pde",
    "Mast Court",
    "Main St",
    "Dory Close",
    "Foote St",
    "Gordon Rd",
    "Babamande St",
  ],
  Thornlands: [
    "Davenport St",
    "Truscot Pl",
    "Hermitage Cres",
    "Island Outlook Ave",
    "Ziegenfusz Rd",
    "Cecilia Close",
    "Butternut Circuit",
    "Thornlands Rd",
    "Wunulla St",
  ],
  Tingalpa: ["Annette Street", "Abbeyfeale St", "Macleay Cres"],
  "Victoria Point": [
    "Barcrest Dr",
    "Weber Court",
    "Kestrel Court",
    "Lindabel Court",
    "Parklane Rd",
    "Waratah Ave",
    "Bunker Rd",
    "Whipbird Circuit",
    "Dunnart St",
    "Creekside Circuit East",
    "Driftwood St",
  ],
  "Wellington Point": ["Liner St", "Hoskins Dr", "Bayview St"],
  Wynnum: ["Nemarra St", "Picton Pde", "Marty St", "Scanlen Cres"],
  "Wynnum West": ["Nemarra St", "Michael St"],
  "Chapel Hill": ["Brushbox Court", "Goolman Pl"],
  Darra: ["Lee Rd"],
  Doolandella: ["St Mary's Close", "Peacock St"],
  "Forest Lake": ["Leichhardt Circuit", "Brushwood Circuit", "Paluna Pl"],
  Heathwood: ["Rise Pl"],
  "Jamboree Heights": ["Mistral St"],
  Jindalee: ["Mankinna St", "Curragundi Rd"],
  "Middle Park": ["Burwick Close"],
  Oxley: ["Woodgate St"],
  Paddington: ["Fernberg Rd", "Guthrie St"],
  "Sinnamon Park": ["McPherson Rd", "Rosemount St"],
  Toowong: ["Gilrey St"],
  // ... (all other locations from previous list)
};
